import type { MediaPair } from "@/lib/media/types";

/**
 * Processed asset map. Components read URLs from here — never hard-code public paths.
 */
export const media = {
  heroTexture: {
    id: "hero-texture",
    desktop: "/media/desktop/hero-texture-desktop.webp",
    mobile: "/media/mobile/hero-texture-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1080,
    widthMobile: 608,
    heightMobile: 1080,
    alt: {
      tr: "Doğal ahşap talaşı dokusu",
      en: "Natural wood shavings texture",
    },
    caption: {
      tr: "Doku referansı — lisanslı fotoğraf.",
      en: "Texture reference — licensed photograph.",
    },
    focal: { desktop: { x: 0.5, y: 0.45 }, mobile: { x: 0.5, y: 0.42 } },
    preload: true,
  },
  heroPoultry: {
    id: "hero-poultry",
    desktop: "/media/desktop/hero-poultry-desktop.webp",
    mobile: "/media/mobile/hero-poultry-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1080,
    widthMobile: 608,
    heightMobile: 1080,
    alt: {
      tr: "Damızlık kümes ortamında tavuklar",
      en: "Chickens in a breeder poultry house",
    },
    caption: {
      tr: "Kullanım alanı görseli — lisanslı fotoğraf, işletmemize ait değildir.",
      en: "Application imagery — licensed photograph, not our facility.",
    },
    focal: { desktop: { x: 0.5, y: 0.48 }, mobile: { x: 0.5, y: 0.46 } },
  },
  heroHorse: {
    id: "hero-horse",
    desktop: "/media/desktop/hero-horse-desktop.webp",
    mobile: "/media/mobile/hero-horse-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1080,
    widthMobile: 608,
    heightMobile: 1080,
    alt: {
      tr: "Ahırda atlar",
      en: "Horses in barn stalls",
    },
    caption: {
      tr: "Kullanım alanı görseli — lisanslı fotoğraf, işletmemize ait değildir.",
      en: "Application imagery — licensed photograph, not our facility.",
    },
    focal: { desktop: { x: 0.48, y: 0.4 }, mobile: { x: 0.5, y: 0.38 } },
  },
  heroCattle: {
    id: "hero-cattle",
    desktop: "/media/desktop/hero-cattle-desktop.webp",
    mobile: "/media/mobile/hero-cattle-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1080,
    widthMobile: 608,
    heightMobile: 1080,
    alt: {
      tr: "Sığır ve buzağı barınağı",
      en: "Cattle and calf housing",
    },
    caption: {
      tr: "Kullanım alanı görseli — lisanslı fotoğraf, işletmemize ait değildir.",
      en: "Application imagery — licensed photograph, not our facility.",
    },
    focal: { desktop: { x: 0.5, y: 0.46 }, mobile: { x: 0.5, y: 0.44 } },
  },
  heroLogs: {
    id: "hero-logs",
    desktop: "/media/desktop/hero-logs-desktop.webp",
    mobile: "/media/mobile/hero-logs-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1080,
    widthMobile: 608,
    heightMobile: 1080,
    alt: {
      tr: "Taze kesilmiş uzun tomruk istifleri",
      en: "Fresh-cut long timber stacks",
    },
    caption: {
      tr: "Hammadde referansı — lisanslı tomruk fotoğrafı; saha görüntümüz değildir.",
      en: "Raw-material reference — licensed timber photograph, not our yard.",
    },
    focal: { desktop: { x: 0.55, y: 0.48 }, mobile: { x: 0.62, y: 0.45 } },
  },
  heroDispatch: {
    id: "hero-dispatch",
    desktop: "/media/desktop/hero-dispatch-desktop.webp",
    mobile: "/media/mobile/hero-dispatch-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1080,
    widthMobile: 608,
    heightMobile: 1080,
    alt: {
      tr: "Elazığ tesisinden çıkan paketli talaş yüklü kamyon",
      en: "Truck loaded with bagged shavings leaving the Elazığ facility",
    },
    focal: { desktop: { x: 0.46, y: 0.48 }, mobile: { x: 0.4, y: 0.5 } },
  },
  rawLogs: {
    id: "raw-logs",
    desktop: "/media/desktop/raw-logs-desktop.webp",
    mobile: "/media/mobile/raw-logs-mobile.webp",
    widthDesktop: 1153,
    heightDesktop: 1441,
    widthMobile: 778,
    heightMobile: 1080,
    alt: {
      tr: "Elazığ Yurtbaşı tesis sahasında tomruk yığını",
      en: "Timber logs in the Yurtbaşı, Elazığ production yard",
    },
    focal: { desktop: { x: 0.52, y: 0.46 }, mobile: { x: 0.5, y: 0.42 } },
  },
  rawLogsDetail: {
    id: "raw-logs-detail",
    desktop: "/media/desktop/raw-logs-detail-desktop.webp",
    mobile: "/media/mobile/raw-logs-detail-mobile.webp",
    widthDesktop: 1153,
    heightDesktop: 769,
    widthMobile: 864,
    heightMobile: 1080,
    alt: {
      tr: "Elazığ sahasında taze kesilmiş tomruk detayı",
      en: "Fresh-cut logs in the Elazığ yard",
    },
    focal: { desktop: { x: 0.48, y: 0.38 }, mobile: { x: 0.5, y: 0.32 } },
  },
  productionMachine: {
    id: "production-machine",
    desktop: "/media/desktop/production-machine-desktop.webp",
    mobile: "/media/mobile/production-machine-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1081,
    widthMobile: 864,
    heightMobile: 1080,
    alt: {
      tr: "Bıçkıhanede kesilen tomruk",
      en: "A log being sawn in a mill",
    },
    caption: {
      tr: "Üretim referansı — lisanslı bıçkıhane fotoğrafı; tesisimizin içi değildir.",
      en: "Production reference — licensed mill photograph, not our factory interior.",
    },
    focal: { desktop: { x: 0.58, y: 0.48 }, mobile: { x: 0.62, y: 0.5 } },
  },
  productShavings: {
    id: "product-shavings-detail",
    desktop: "/media/desktop/product-shavings-detail-desktop.webp",
    mobile: "/media/mobile/product-shavings-detail-mobile.webp",
    widthDesktop: 1153,
    heightDesktop: 1441,
    widthMobile: 864,
    heightMobile: 1080,
    alt: {
      tr: "Doğal ahşap talaşının yakın çekimi",
      en: "Close view of natural wood shavings",
    },
    focal: { desktop: { x: 0.5, y: 0.55 }, mobile: { x: 0.5, y: 0.52 } },
  },
  poultryBedding: {
    id: "poultry-bedding",
    desktop: "/media/desktop/poultry-bedding-desktop.webp",
    mobile: "/media/mobile/poultry-bedding-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1280,
    widthMobile: 864,
    heightMobile: 1080,
    alt: {
      tr: "Kümes ortamında tavuklar",
      en: "Chickens in a poultry house",
    },
    caption: {
      tr: "Kullanım alanı görseli — lisanslı fotoğraf, işletmemize ait değildir.",
      en: "Application imagery — licensed photograph, not our facility.",
    },
    focal: { desktop: { x: 0.5, y: 0.5 }, mobile: { x: 0.5, y: 0.48 } },
  },
  horseBedding: {
    id: "horse-bedding",
    desktop: "/media/desktop/horse-bedding-desktop.webp",
    mobile: "/media/mobile/horse-bedding-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1280,
    widthMobile: 864,
    heightMobile: 1080,
    alt: {
      tr: "Ahırda at",
      en: "Horse in a stable",
    },
    caption: {
      tr: "Kullanım alanı görseli — lisanslı fotoğraf, işletmemize ait değildir.",
      en: "Application imagery — licensed photograph, not our facility.",
    },
    focal: { desktop: { x: 0.45, y: 0.42 }, mobile: { x: 0.48, y: 0.4 } },
  },
  cattleBedding: {
    id: "cattle-bedding",
    desktop: "/media/desktop/cattle-bedding-desktop.webp",
    mobile: "/media/mobile/cattle-bedding-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1280,
    widthMobile: 864,
    heightMobile: 1080,
    alt: {
      tr: "Sığır barınağı",
      en: "Cattle in a livestock barn",
    },
    caption: {
      tr: "Kullanım alanı görseli — lisanslı fotoğraf, işletmemize ait değildir.",
      en: "Application imagery — licensed photograph, not our facility.",
    },
    focal: { desktop: { x: 0.5, y: 0.48 }, mobile: { x: 0.5, y: 0.45 } },
  },
  logisticsTruck: {
    id: "logistics-truck",
    desktop: "/media/desktop/logistics-truck-desktop.webp",
    mobile: "/media/mobile/logistics-truck-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1081,
    widthMobile: 864,
    heightMobile: 1080,
    alt: {
      tr: "Elazığ tesisinden çıkan paketli talaş yüklü kamyon",
      en: "Truck loaded with bagged shavings leaving the Elazığ facility",
    },
    focal: { desktop: { x: 0.48, y: 0.46 }, mobile: { x: 0.42, y: 0.48 } },
  },
  shavingsTexture: {
    id: "wood-shavings-texture",
    desktop: "/media/desktop/wood-shavings-texture-desktop.webp",
    mobile: "/media/mobile/wood-shavings-texture-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1280,
    widthMobile: 864,
    heightMobile: 1080,
    alt: {
      tr: "Ahşap talaşı dokusu",
      en: "Wood shavings texture",
    },
    caption: {
      tr: "Doku referansı — lisanslı fotoğraf.",
      en: "Texture reference — licensed photograph.",
    },
    focal: { desktop: { x: 0.5, y: 0.5 }, mobile: { x: 0.5, y: 0.5 } },
  },
  bulkHandling: {
    id: "bulk-handling",
    desktop: "/media/desktop/bulk-handling-desktop.webp",
    mobile: "/media/mobile/bulk-handling-mobile.webp",
    widthDesktop: 1920,
    heightDesktop: 1280,
    widthMobile: 864,
    heightMobile: 1080,
    alt: {
      tr: "Taze kesilmiş uzun tomruk istifleri",
      en: "Stacks of freshly cut long timber",
    },
    caption: {
      tr: "Hammadde referansı — lisanslı tomruk istif fotoğrafı; saha görüntümüz değildir.",
      en: "Raw-material reference — licensed timber stack, not our yard.",
    },
    focal: { desktop: { x: 0.5, y: 0.5 }, mobile: { x: 0.5, y: 0.48 } },
  },
  facilityYard: {
    id: "facility-yard",
    desktop: "/media/desktop/facility-yard-desktop.webp",
    mobile: "/media/mobile/facility-yard-mobile.webp",
    widthDesktop: 1845,
    heightDesktop: 1153,
    widthMobile: 864,
    heightMobile: 1080,
    alt: {
      tr: "Elazığ Yurtbaşı üretim sahası ve tesis binası",
      en: "Production yard and building in Yurtbaşı, Elazığ",
    },
    focal: { desktop: { x: 0.78, y: 0.42 }, mobile: { x: 0.82, y: 0.4 } },
  },
} satisfies Record<string, MediaPair>;

export const heroSlides: MediaPair[] = [
  media.heroTexture,
  media.heroPoultry,
  media.heroHorse,
  media.heroCattle,
  media.heroLogs,
  media.heroDispatch,
];

export type MediaKey = keyof typeof media;
